-- ECLIPSE DUEL clean database install
-- This schema is independent from every old VANTA/minigame/arcana table.

create extension if not exists pgcrypto;

create table if not exists public.eclipse_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '신입 결투가',
  player_code text not null unique,
  avatar text not null default 'eclipse',
  status_message text not null default '새로운 덱을 연구하는 중',
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  xp integer not null default 0 check (xp >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.eclipse_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  coins integer not null default 500 check (coins >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.eclipse_collections (
  user_id uuid not null references auth.users(id) on delete cascade,
  card_id text not null,
  quantity integer not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, card_id)
);

create table if not exists public.eclipse_decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '기본 덱',
  cards jsonb not null default '[]'::jsonb,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists eclipse_one_active_deck_per_user
on public.eclipse_decks(user_id)
where is_active = true;

create table if not exists public.eclipse_rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid references auth.users(id) on delete set null,
  public_match boolean not null default false,
  status text not null default 'waiting' check (status in ('waiting','active','finished','cancelled')),
  ready_host boolean not null default false,
  ready_guest boolean not null default false,
  state jsonb,
  version integer not null default 0,
  winner_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists eclipse_rooms_waiting_idx
on public.eclipse_rooms(public_match, status, created_at)
where guest_id is null;

create table if not exists public.eclipse_private_states (
  room_id uuid not null references public.eclipse_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists public.eclipse_global_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  body text not null check (char_length(body) between 1 and 180),
  created_at timestamptz not null default now()
);

create index if not exists eclipse_global_messages_created_idx
on public.eclipse_global_messages(created_at desc);

create table if not exists public.eclipse_room_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.eclipse_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null,
  body text not null check (char_length(body) between 1 and 180),
  created_at timestamptz not null default now()
);

create index if not exists eclipse_room_messages_room_idx
on public.eclipse_room_messages(room_id, created_at desc);

create table if not exists public.eclipse_friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);

create unique index if not exists eclipse_pending_friend_pair
on public.eclipse_friend_requests(sender_id, receiver_id)
where status = 'pending';

create table if not exists public.eclipse_friends (
  user_id uuid not null references auth.users(id) on delete cascade,
  friend_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, friend_id),
  check (user_id <> friend_id)
);

create table if not exists public.eclipse_match_rewards (
  room_id uuid not null references public.eclipse_rooms(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  coins integer not null,
  xp integer not null,
  won boolean not null,
  created_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create or replace function public.eclipse_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists eclipse_profiles_touch on public.eclipse_profiles;
create trigger eclipse_profiles_touch before update on public.eclipse_profiles
for each row execute function public.eclipse_touch_updated_at();

drop trigger if exists eclipse_wallets_touch on public.eclipse_wallets;
create trigger eclipse_wallets_touch before update on public.eclipse_wallets
for each row execute function public.eclipse_touch_updated_at();

drop trigger if exists eclipse_decks_touch on public.eclipse_decks;
create trigger eclipse_decks_touch before update on public.eclipse_decks
for each row execute function public.eclipse_touch_updated_at();

drop trigger if exists eclipse_rooms_touch on public.eclipse_rooms;
create trigger eclipse_rooms_touch before update on public.eclipse_rooms
for each row execute function public.eclipse_touch_updated_at();

drop trigger if exists eclipse_private_touch on public.eclipse_private_states;
create trigger eclipse_private_touch before update on public.eclipse_private_states
for each row execute function public.eclipse_touch_updated_at();

create or replace function public.eclipse_open_pack(
  p_user uuid,
  p_cost integer,
  p_cards jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
  v_item record;
begin
  update public.eclipse_wallets
  set coins = coins - p_cost
  where user_id = p_user and coins >= p_cost
  returning coins into v_balance;

  if v_balance is null then
    raise exception '코인이 부족합니다.';
  end if;

  for v_item in
    select card_id, quantity
    from jsonb_to_recordset(p_cards) as x(card_id text, quantity integer)
  loop
    insert into public.eclipse_collections(user_id, card_id, quantity)
    values (p_user, v_item.card_id, greatest(1, v_item.quantity))
    on conflict (user_id, card_id)
    do update set quantity = public.eclipse_collections.quantity + excluded.quantity, updated_at = now();
  end loop;

  return v_balance;
end;
$$;

create or replace function public.eclipse_commit_match(
  p_room_id uuid,
  p_expected_version integer,
  p_state jsonb,
  p_status text,
  p_winner uuid,
  p_private_states jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_updated integer;
begin
  update public.eclipse_rooms
  set state = p_state,
      status = p_status,
      winner_id = p_winner,
      version = version + 1,
      updated_at = now()
  where id = p_room_id and version = p_expected_version;

  get diagnostics v_updated = row_count;
  if v_updated = 0 then
    return false;
  end if;

  insert into public.eclipse_private_states(room_id, user_id, state)
  select p_room_id, x.user_id, x.state
  from jsonb_to_recordset(p_private_states) as x(user_id uuid, state jsonb)
  on conflict (room_id, user_id)
  do update set state = excluded.state, updated_at = now();

  return true;
end;
$$;

create or replace function public.eclipse_reward_match(
  p_room_id uuid,
  p_user uuid,
  p_coins integer,
  p_xp integer,
  p_won boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inserted integer;
begin
  insert into public.eclipse_match_rewards(room_id, user_id, coins, xp, won)
  values (p_room_id, p_user, p_coins, p_xp, p_won)
  on conflict (room_id, user_id) do nothing;

  get diagnostics v_inserted = row_count;
  if v_inserted = 0 then
    return false;
  end if;

  insert into public.eclipse_wallets(user_id, coins)
  values (p_user, p_coins)
  on conflict (user_id)
  do update set coins = public.eclipse_wallets.coins + excluded.coins, updated_at = now();

  update public.eclipse_profiles
  set xp = xp + p_xp,
      wins = wins + case when p_won then 1 else 0 end,
      losses = losses + case when p_won then 0 else 1 end
  where user_id = p_user;

  return true;
end;
$$;

revoke all on function public.eclipse_open_pack(uuid, integer, jsonb) from public, anon, authenticated;
revoke all on function public.eclipse_commit_match(uuid, integer, jsonb, text, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.eclipse_reward_match(uuid, uuid, integer, integer, boolean) from public, anon, authenticated;
grant execute on function public.eclipse_open_pack(uuid, integer, jsonb) to service_role;
grant execute on function public.eclipse_commit_match(uuid, integer, jsonb, text, uuid, jsonb) to service_role;
grant execute on function public.eclipse_reward_match(uuid, uuid, integer, integer, boolean) to service_role;

alter table public.eclipse_profiles enable row level security;
alter table public.eclipse_wallets enable row level security;
alter table public.eclipse_collections enable row level security;
alter table public.eclipse_decks enable row level security;
alter table public.eclipse_rooms enable row level security;
alter table public.eclipse_private_states enable row level security;
alter table public.eclipse_global_messages enable row level security;
alter table public.eclipse_room_messages enable row level security;
alter table public.eclipse_friend_requests enable row level security;
alter table public.eclipse_friends enable row level security;
alter table public.eclipse_match_rewards enable row level security;

drop policy if exists eclipse_profiles_read on public.eclipse_profiles;
create policy eclipse_profiles_read on public.eclipse_profiles for select to authenticated using (true);
drop policy if exists eclipse_profiles_update_own on public.eclipse_profiles;
-- Profile writes are handled only by the trusted Render API.

drop policy if exists eclipse_wallet_read_own on public.eclipse_wallets;
create policy eclipse_wallet_read_own on public.eclipse_wallets for select to authenticated using (auth.uid() = user_id);
drop policy if exists eclipse_collection_read_own on public.eclipse_collections;
create policy eclipse_collection_read_own on public.eclipse_collections for select to authenticated using (auth.uid() = user_id);
drop policy if exists eclipse_decks_read_own on public.eclipse_decks;
create policy eclipse_decks_read_own on public.eclipse_decks for select to authenticated using (auth.uid() = user_id);

drop policy if exists eclipse_rooms_participants_read on public.eclipse_rooms;
create policy eclipse_rooms_participants_read on public.eclipse_rooms for select to authenticated
using (auth.uid() = host_id or auth.uid() = guest_id);

drop policy if exists eclipse_global_chat_read on public.eclipse_global_messages;
create policy eclipse_global_chat_read on public.eclipse_global_messages for select to authenticated using (true);

drop policy if exists eclipse_room_chat_read on public.eclipse_room_messages;
create policy eclipse_room_chat_read on public.eclipse_room_messages for select to authenticated
using (exists (
  select 1 from public.eclipse_rooms r
  where r.id = room_id and (r.host_id = auth.uid() or r.guest_id = auth.uid())
));

drop policy if exists eclipse_friend_requests_read on public.eclipse_friend_requests;
create policy eclipse_friend_requests_read on public.eclipse_friend_requests for select to authenticated
using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists eclipse_friends_read on public.eclipse_friends;
create policy eclipse_friends_read on public.eclipse_friends for select to authenticated using (auth.uid() = user_id);

drop policy if exists eclipse_rewards_read on public.eclipse_match_rewards;
create policy eclipse_rewards_read on public.eclipse_match_rewards for select to authenticated using (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select on public.eclipse_profiles, public.eclipse_wallets, public.eclipse_collections, public.eclipse_decks,
  public.eclipse_rooms, public.eclipse_global_messages, public.eclipse_room_messages,
  public.eclipse_friend_requests, public.eclipse_friends, public.eclipse_match_rewards to authenticated;

-- Private states intentionally have no authenticated policy or grant.
revoke all on public.eclipse_private_states from anon, authenticated;

-- Realtime publication, safely idempotent.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'eclipse_rooms'
  ) then
    alter publication supabase_realtime add table public.eclipse_rooms;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'eclipse_global_messages'
  ) then
    alter publication supabase_realtime add table public.eclipse_global_messages;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'eclipse_room_messages'
  ) then
    alter publication supabase_realtime add table public.eclipse_room_messages;
  end if;
end $$;

select
  to_regclass('public.eclipse_profiles') is not null as profiles_ready,
  to_regclass('public.eclipse_decks') is not null as decks_ready,
  to_regclass('public.eclipse_rooms') is not null as rooms_ready,
  to_regclass('public.eclipse_private_states') is not null as private_states_ready,
  to_regclass('public.eclipse_global_messages') is not null as chat_ready;
