export type ProfileCosmeticKind = 'background' | 'frame' | 'emblem' | 'sleeve' | 'nickname';
export type ProfileCosmetic = {
  id: string;
  kind: ProfileCosmeticKind;
  name: string;
  price: number;
  rarity: 'rare' | 'epic' | 'legendary';
  description: string;
  accent: string;
  glyph?: string;
};

export const PROFILE_COSMETICS: ProfileCosmetic[] = [
  { id: 'bg_eclipse_nexus', kind: 'background', name: '일식의 중추', price: 700, rarity: 'rare', description: '푸른 일식과 궤도 링이 흐르는 결투가 프로필 배경.', accent: '#66c8ff' },
  { id: 'bg_solar_cathedral', kind: 'background', name: '태양 성당', price: 1100, rarity: 'epic', description: '황금빛 성광과 스테인드 글라스가 펼쳐지는 배경.', accent: '#ffc56a' },
  { id: 'bg_lunar_archive', kind: 'background', name: '월영 기록고', price: 1100, rarity: 'epic', description: '달빛 문양과 떠다니는 기록 파편으로 구성된 배경.', accent: '#91a8ff' },
  { id: 'bg_void_throne', kind: 'background', name: '공허의 왕좌', price: 1700, rarity: 'legendary', description: '균열과 암흑 성운이 뒤틀리는 전설급 프로필 배경.', accent: '#bd78ff' },
  { id: 'frame_aurora', kind: 'frame', name: '오로라 프레임', price: 500, rarity: 'rare', description: '청록과 보랏빛이 은은하게 흐르는 프로필 프레임.', accent: '#6de8ff' },
  { id: 'frame_royal', kind: 'frame', name: '왕실 금장', price: 900, rarity: 'epic', description: '금빛 각인과 왕실 문양을 두른 프로필 프레임.', accent: '#ffd16d' },
  { id: 'frame_rift', kind: 'frame', name: '균열 파편', price: 1250, rarity: 'epic', description: '공간 파편이 가장자리에서 떠오르는 프레임.', accent: '#a977ff' },
  { id: 'frame_astral', kind: 'frame', name: '성계의 관', price: 1800, rarity: 'legendary', description: '별빛 궤도와 광휘가 회전하는 전설급 프레임.', accent: '#81a4ff' },
  { id: 'emblem_solar_crest', kind: 'emblem', name: '태양검 문장', price: 650, rarity: 'rare', description: '프로필 위에 장착하는 황금 태양검 문양.', accent: '#ffc866', glyph: '✦' },
  { id: 'emblem_lunar_eye', kind: 'emblem', name: '월식의 눈', price: 800, rarity: 'epic', description: '달의 궤도와 눈동자가 겹치는 월영 문양.', accent: '#9eb5ff', glyph: '◉' },
  { id: 'emblem_kaiser_crown', kind: 'emblem', name: '카이저 황관', price: 1000, rarity: 'epic', description: '황제기갑의 지휘권을 상징하는 금속 왕관.', accent: '#ffd37f', glyph: '♛' },
  { id: 'emblem_rift_omega', kind: 'emblem', name: '균열 오메가', price: 1400, rarity: 'epic', description: '공간 균열이 Ω 형태로 응축된 공명 문양.', accent: '#c58cff', glyph: 'Ω' },
  { id: 'emblem_astral_wings', kind: 'emblem', name: '성해의 쌍익', price: 1900, rarity: 'legendary', description: '별바다를 가르는 두 광익이 펼쳐지는 전설 문양.', accent: '#83dcff', glyph: '✧' },
  { id: 'emblem_neon_star', kind: 'emblem', name: '네온 스타', price: 950, rarity: 'epic', description: '청보라 네온 별이 점멸하는 움직이는 프로필 아이콘.', accent: '#77e4ff', glyph: '✹' },
  { id: 'emblem_midnight_moon', kind: 'emblem', name: '미드나잇 문', price: 980, rarity: 'epic', description: '초승달 잔광이 퍼지는 심야 문양.', accent: '#b7c7ff', glyph: '☽' },
  { id: 'emblem_blossom_seal', kind: 'emblem', name: '블러썸 실', price: 1100, rarity: 'epic', description: '꽃잎 입자가 맴도는 화사한 프로필 문양.', accent: '#ffb1df', glyph: '❀' },
  { id: 'emblem_royal_lily', kind: 'emblem', name: '로열 릴리', price: 1450, rarity: 'epic', description: '고풍스러운 백합 문장이 금빛으로 반짝이는 문양.', accent: '#ffd685', glyph: '❖' },
  { id: 'emblem_tidal_orbit', kind: 'emblem', name: '타이달 오비트', price: 1650, rarity: 'legendary', description: '푸른 물결 궤도가 회전하는 전설 프로필 아이콘.', accent: '#71e7ff', glyph: '◌' },
  { id: 'emblem_comet_heart', kind: 'emblem', name: '코멧 하트', price: 1180, rarity: 'epic', description: '작은 혜성이 하트 궤도를 그리며 도는 문양.', accent: '#ffa4d0', glyph: '♥' },
  { id: 'emblem_clock_halo', kind: 'emblem', name: '클락 헤일로', price: 1540, rarity: 'legendary', description: '시계 눈금이 빛 고리로 회전하는 시간 문양.', accent: '#99ebff', glyph: '◔' },
  { id: 'emblem_storm_sigil', kind: 'emblem', name: '스톰 시질', price: 1320, rarity: 'epic', description: '번개 모양의 잔광이 주위를 맴도는 폭풍 문양.', accent: '#8dc9ff', glyph: '⚡' },
  { id: 'emblem_prism_butterfly', kind: 'emblem', name: '프리즘 버터플라이', price: 1380, rarity: 'epic', description: '프리즘 날개가 펼쳐졌다 접히듯 반짝이는 프로필 문양.', accent: '#d59bff', glyph: '✣' },
  { id: 'emblem_eclipse_crown', kind: 'emblem', name: '이클립스 크라운', price: 1760, rarity: 'legendary', description: '작은 일식 고리 위로 왕관 광채가 떠오르는 전설 문양.', accent: '#ffd17f', glyph: '♚' },
  { id: 'emblem_sakura_halo', kind: 'emblem', name: '사쿠라 헤일로', price: 1260, rarity: 'epic', description: '벚꽃빛 헤일로가 숨 쉬듯 피고 지는 프로필 문양.', accent: '#ffabd8', glyph: '❁' },
  { id: 'emblem_comet_arrow', kind: 'emblem', name: '코멧 애로우', price: 1480, rarity: 'epic', description: '혜성 꼬리가 사선으로 스쳐 지나가는 역동적인 문양.', accent: '#8ddfff', glyph: '➳' },
  { id: 'emblem_arcane_node', kind: 'emblem', name: '아케인 노드', price: 1690, rarity: 'legendary', description: '마력 노드가 순차적으로 점등되는 전설 프로필 문양.', accent: '#be8dff', glyph: '✺' },
  { id: 'sleeve_eclipse_black', kind: 'sleeve', name: '일식 블랙 슬리브', price: 450, rarity: 'rare', description: '검은 일식 링과 은빛 E 문장이 새겨진 카드 보호 슬리브.', accent: '#7788ff', glyph: 'E' },
  { id: 'sleeve_solar_flare', kind: 'sleeve', name: '솔라 플레어 슬리브', price: 650, rarity: 'rare', description: '붉은 태양 홍염이 카드 뒷면을 감싸는 슬리브.', accent: '#ff985d', glyph: '☀' },
  { id: 'sleeve_lunar_glass', kind: 'sleeve', name: '루나 글라스 슬리브', price: 800, rarity: 'epic', description: '푸른 유리와 초승달 궤도로 빛나는 슬리브.', accent: '#9cb5ff', glyph: '☾' },
  { id: 'sleeve_kaiser_chrome', kind: 'sleeve', name: '카이저 크롬 슬리브', price: 1050, rarity: 'epic', description: '황제기갑 장갑판처럼 분할된 크롬 카드 슬리브.', accent: '#d9c68d', glyph: 'K' },
  { id: 'sleeve_void_prism', kind: 'sleeve', name: '보이드 프리즘 슬리브', price: 1350, rarity: 'epic', description: '보랏빛 프리즘 균열이 회전하는 공허 슬리브.', accent: '#c17cff', glyph: '◇' },
  { id: 'sleeve_astral_navy', kind: 'sleeve', name: '아스트라 네이비 슬리브', price: 1700, rarity: 'legendary', description: '성해함대 항로와 별빛 함선 문장이 새겨진 전설 슬리브.', accent: '#69d8ff', glyph: '✶' },
  { id: 'sleeve_starry_night', kind: 'sleeve', name: '밤하늘 슬리브', price: 720, rarity: 'rare', description: '별이 총총한 밤하늘과 잔잔한 은하 무늬가 감도는 슬리브.', accent: '#8bbcff', glyph: '✦' },
  { id: 'sleeve_neon_sign', kind: 'sleeve', name: '네온 사인 슬리브', price: 980, rarity: 'epic', description: '간판 같은 네온 선과 도형이 반짝이는 카드 슬리브.', accent: '#62f0ff', glyph: 'N' },
  { id: 'sleeve_blossom_garden', kind: 'sleeve', name: '블러썸 가든 슬리브', price: 1020, rarity: 'epic', description: '꽃무늬와 분홍빛 장식이 포근하게 퍼지는 슬리브.', accent: '#ff9ad6', glyph: '❀' },
  { id: 'sleeve_holo_checker', kind: 'sleeve', name: '홀로 체커 슬리브', price: 1280, rarity: 'epic', description: '홀로그램 체커보드 패턴이 각도에 따라 반짝이는 슬리브.', accent: '#a7d8ff', glyph: '◫' },
  { id: 'sleeve_royal_wallpaper', kind: 'sleeve', name: '로열 월페이퍼 슬리브', price: 1380, rarity: 'epic', description: '고풍스러운 금장 벽지 무늬가 새겨진 우아한 슬리브.', accent: '#e9c978', glyph: '❖' },
  { id: 'sleeve_moonlit_window', kind: 'sleeve', name: '문라이트 윈도우 슬리브', price: 1680, rarity: 'legendary', description: '달빛 창문과 커튼 그림자가 겹쳐지는 전설 슬리브.', accent: '#a8c6ff', glyph: '☽' },
  { id: 'bg_nebula_vortex', kind: 'background', name: '성운 와류', price: 2300, rarity: 'legendary', description: '성운 입자와 궤도광이 끊임없이 회전하는 애니메이션 프로필 배경.', accent: '#8d7cff' },
  { id: 'bg_chrono_rift', kind: 'background', name: '크로노 균열', price: 2600, rarity: 'legendary', description: '시간 균열과 시계 문양이 흐르며 왜곡되는 애니메이션 배경.', accent: '#66d8ff' },
  { id: 'bg_aurora_tide', kind: 'background', name: '오로라 타이드', price: 1900, rarity: 'epic', description: '오로라 물결과 잔광이 천천히 흘러가는 애니메이션 프로필 배경.', accent: '#69efd1' },
  { id: 'bg_neon_midnight', kind: 'background', name: '네온 미드나잇', price: 2300, rarity: 'legendary', description: '심야 도시의 네온 선이 스캔라인처럼 지나가는 애니메이션 배경.', accent: '#7ae0ff' },
  { id: 'bg_starfall_garden', kind: 'background', name: '별꽃 정원', price: 2100, rarity: 'legendary', description: '꽃잎과 별조각이 떠다니는 애니메이션 프로필 배경.', accent: '#f3a7ff' },
  { id: 'frame_prismatic_loop', kind: 'frame', name: '프리즘 루프', price: 2200, rarity: 'legendary', description: '무지갯빛 광선이 테두리를 따라 순환하는 애니메이션 프레임.', accent: '#f19cff' },
  { id: 'frame_ember_crown', kind: 'frame', name: '홍염의 관', price: 2400, rarity: 'legendary', description: '불꽃 입자가 테두리를 타고 상승하는 애니메이션 전설 프레임.', accent: '#ff9a5f' },
  { id: 'frame_neon_circuit', kind: 'frame', name: '네온 서킷', price: 2050, rarity: 'epic', description: '회로선이 테두리를 따라 질주하는 네온 프레임.', accent: '#66efff' },
  { id: 'frame_moonlace', kind: 'frame', name: '문레이스', price: 2150, rarity: 'legendary', description: '달빛 리본이 조용히 흐르며 반짝이는 우아한 프레임.', accent: '#c7d6ff' },
  { id: 'frame_blossom_arc', kind: 'frame', name: '블러썸 아크', price: 2250, rarity: 'legendary', description: '꽃잎 장식이 맴돌며 피어나는 화사한 프레임.', accent: '#ffb0e5' },
  { id: 'frame_royal_window', kind: 'frame', name: '로열 윈도우', price: 2350, rarity: 'legendary', description: '스테인드글라스 광채가 부드럽게 이동하는 왕실 프레임.', accent: '#ffd985' },
  { id: 'nickname_rainbow', kind: 'nickname', name: '레인보우 시프트', price: 900, rarity: 'epic', description: '닉네임을 따라 무지개 그라데이션이 계속 흐릅니다. 모든 플레이어 화면에 적용됩니다.', accent: '#ff74d5' },
  { id: 'nickname_neon', kind: 'nickname', name: '네온 펄스', price: 850, rarity: 'epic', description: '청보라 네온이 부드럽게 점멸하는 닉네임 효과.', accent: '#6ee8ff' },
  { id: 'nickname_starlight', kind: 'nickname', name: '스타라이트', price: 1200, rarity: 'epic', description: '별빛이 글자 위를 스쳐 지나가는 반짝임 애니메이션.', accent: '#c4dcff' },
  { id: 'nickname_ember', kind: 'nickname', name: '홍염 파동', price: 1300, rarity: 'epic', description: '붉은색과 금색이 불꽃처럼 요동치는 닉네임 효과.', accent: '#ff945d' },
  { id: 'nickname_glitch', kind: 'nickname', name: '보이드 글리치', price: 1600, rarity: 'legendary', description: '공허색 잔상과 짧은 디지털 왜곡이 발생하는 전설 닉네임 효과.', accent: '#bd7cff' },
  { id: 'nickname_aurora', kind: 'nickname', name: '오로라 웨이브', price: 1800, rarity: 'legendary', description: '청록·보라·푸른빛이 물결처럼 이동하는 전설 닉네임 애니메이션.', accent: '#73e7da' },
  { id: 'nickname_gold', kind: 'nickname', name: '황제의 서명', price: 2100, rarity: 'legendary', description: '금빛 하이라이트가 왕관처럼 반복해서 흐르는 전설 닉네임 효과.', accent: '#ffd06f' },
  { id: 'bg_sticker_nikke', kind: 'background', name: '스티커 월 · 니케', price: 1880, rarity: 'legendary', description: '니케 이모티콘 6종을 누끼 스티커처럼 붙여 넣은 프로필 배경.', accent: '#ffcf92' },
  { id: 'bg_sticker_bluearchive', kind: 'background', name: '스티커 월 · 도로롱', price: 1880, rarity: 'legendary', description: '도로롱 이모티콘 6종을 코팅 스티커처럼 흩뿌린 프로필 배경.', accent: '#9ad8ff' },
  { id: 'bg_sticker_genshin', kind: 'background', name: '스티커 월 · 트릭컬', price: 1880, rarity: 'legendary', description: '트릭컬 이모티콘 6종을 다이어리처럼 배치한 프로필 배경.', accent: '#ffe18f' },
  { id: 'bg_sticker_hsr', kind: 'background', name: '스티커 월 · 가디언테일즈', price: 1880, rarity: 'legendary', description: '가디언테일즈 이모티콘 6종이 둥둥 떠 있는 프로필 배경.', accent: '#d6c4ff' },
  { id: 'bg_sticker_arcade', kind: 'background', name: '스티커 월 · 이렘티콘', price: 1760, rarity: 'legendary', description: '이렘티콘 이모티콘 6종을 도트 패널 위에 붙인 레트로 배경.', accent: '#98f8ff' },
  { id: 'bg_sticker_wuwa', kind: 'background', name: '프리즘 레이스 오로라', price: 2250, rarity: 'legendary', description: '홀로 레이스 리본과 프리즘 빛결이 천천히 흘러 색이 바뀌는 애니메이션 프로필 배경.', accent: '#9ae7ff' },
  { id: 'bg_clockwork_dawn', kind: 'background', name: '크로노 기어 성역', price: 2500, rarity: 'legendary', description: '금빛 시간륜과 기어 궤도가 계속 회전하듯 움직이고 새벽 광선이 스쳐 가는 애니메이션 배경.', accent: '#ffd98a' },
  { id: 'bg_aurora_grid', kind: 'background', name: '오로라 데이터폴', price: 2350, rarity: 'legendary', description: '청록 오로라와 데이터 격자가 폭포처럼 흘러내리며 파동치는 미래형 애니메이션 배경.', accent: '#8bffd4' },
  { id: 'bg_midnight_record', kind: 'background', name: '미드나잇 블랙홀', price: 2600, rarity: 'legendary', description: '심야의 블랙홀 링과 보랏빛 성운이 맥동하며 안쪽으로 빨려 들어가는 듯한 애니메이션 배경.', accent: '#aab6ff' },
  { id: 'bg_starlight_arcade', kind: 'background', name: '스타라이트 하이웨이', price: 2400, rarity: 'legendary', description: '별빛 입자와 네온 레일이 화면을 가로질러 질주하는 속도감 있는 애니메이션 프로필 배경.', accent: '#9cf2ff' },
  { id: 'emblem_sticker_rabbit', kind: 'emblem', name: '스티커 도로롱', price: 760, rarity: 'epic', description: '도로롱 이모티콘을 코팅 스티커처럼 만든 프로필 아이콘.', accent: '#ffc6e2', glyph: '🐰' },
  { id: 'emblem_sticker_angel', kind: 'emblem', name: '스티커 가디언', price: 760, rarity: 'epic', description: '가디언테일즈 이모티콘을 둥근 스티커로 만든 문양.', accent: '#fff3b6', glyph: '😇' },
  { id: 'emblem_sticker_cat', kind: 'emblem', name: '스티커 니케', price: 760, rarity: 'epic', description: '니케 이모티콘을 누끼 스티커처럼 띄운 프로필 아이콘.', accent: '#d7d7ff', glyph: '🐱' },
  { id: 'emblem_sticker_cheer', kind: 'emblem', name: '스티커 트릭컬', price: 760, rarity: 'epic', description: '트릭컬 이모티콘을 응원 스티커처럼 꾸민 문양.', accent: '#9cf2ff', glyph: '🎉' },
  { id: 'emblem_sticker_moon', kind: 'emblem', name: '스티커 이렘티콘', price: 760, rarity: 'epic', description: '이렘티콘 이모티콘을 야광 스티커 느낌으로 표현한 문양.', accent: '#c4d4ff', glyph: '🌙' },
  { id: 'emblem_sticker_crown', kind: 'emblem', name: '스티커 니케 파워', price: 760, rarity: 'epic', description: '니케 파워 표정을 큼직하게 붙여 넣은 문양.', accent: '#ffe19b', glyph: '👑' },
  { id: 'emblem_sticker_gear', kind: 'emblem', name: '스티커 가디언 플라워', price: 760, rarity: 'epic', description: '가디언 꽃 이모티콘이 돌아가는 듯한 메카풍 문양.', accent: '#c5f4ff', glyph: '⚙' },
  { id: 'emblem_sticker_heart', kind: 'emblem', name: '스티커 도로롱 러브', price: 760, rarity: 'epic', description: '도로롱 하트 이모티콘을 겹쳐 만든 문양.', accent: '#ffb3d8', glyph: '💖' },
  { id: 'emblem_sticker_pixel', kind: 'emblem', name: '스티커 이렘 예아', price: 760, rarity: 'epic', description: '이렘티콘 이모티콘을 픽셀 스티커처럼 만든 아이콘.', accent: '#7ce8ff', glyph: '🕹' },
  { id: 'emblem_sticker_comet', kind: 'emblem', name: '스티커 트릭컬 버스트', price: 760, rarity: 'epic', description: '트릭컬 버스트 이모티콘이 휙 지나가는 문양.', accent: '#bceeff', glyph: '☄' },
  { id: 'sleeve_sticker_nikke', kind: 'sleeve', name: '스티커 슬리브 · 니케', price: 920, rarity: 'epic', description: '니케 이모티콘 6종을 누끼 스티커처럼 붙인 카드 슬리브.', accent: '#ffcf92', glyph: '⚙' },
  { id: 'sleeve_sticker_bluearchive', kind: 'sleeve', name: '스티커 슬리브 · 도로롱', price: 920, rarity: 'epic', description: '도로롱 이모티콘 6종을 코팅 스티커처럼 배치한 카드 슬리브.', accent: '#9ad8ff', glyph: '✎' },
  { id: 'sleeve_sticker_genshin', kind: 'sleeve', name: '스티커 슬리브 · 트릭컬', price: 920, rarity: 'epic', description: '트릭컬 이모티콘 6종이 통통 튀게 붙은 카드 뒷면.', accent: '#ffe18f', glyph: '✦' },
  { id: 'sleeve_sticker_hsr', kind: 'sleeve', name: '스티커 슬리브 · 가디언테일즈', price: 920, rarity: 'epic', description: '가디언테일즈 이모티콘 6종이 떠다니는 카드 슬리브.', accent: '#d6c4ff', glyph: '🚄' },
  { id: 'sleeve_sticker_arcade', kind: 'sleeve', name: '스티커 슬리브 · 이렘티콘', price: 920, rarity: 'epic', description: '이렘티콘 이모티콘 6종이 붙은 레트로 카드 뒷면.', accent: '#98f8ff', glyph: '▦' },
  { id: 'sleeve_sticker_wuwa', kind: 'sleeve', name: '프리즘 레이스 슬리브', price: 960, rarity: 'epic', description: '홀로 프리즘과 레이스 패턴이 반짝이는 예쁜 무늬 슬리브.', accent: '#9ae7ff', glyph: '◈' },
  { id: 'sleeve_sticker_eclipse', kind: 'sleeve', name: '오로라 라인 슬리브', price: 960, rarity: 'epic', description: '오로라 선과 유리 파편 무늬가 교차하는 세련된 슬리브.', accent: '#f7d38c', glyph: '◉' },
  { id: 'sleeve_sticker_royal', kind: 'sleeve', name: '로열 다마스크 슬리브', price: 960, rarity: 'epic', description: '고풍스러운 다마스크 금장 무늬로 채운 우아한 슬리브.', accent: '#ffe19b', glyph: '♕' },
  { id: 'sleeve_sticker_sakura', kind: 'sleeve', name: '블러썸 포그 슬리브', price: 960, rarity: 'epic', description: '안개처럼 퍼지는 꽃잎 패턴이 포근한 슬리브.', accent: '#ffbfdc', glyph: '🌸' },
  { id: 'sleeve_sticker_midnight', kind: 'sleeve', name: '미드나잇 네온 슬리브', price: 960, rarity: 'epic', description: '심야 네온 격자와 작은 별 무늬가 반짝이는 슬리브.', accent: '#bcc7ff', glyph: '🌙' },
  { id: 'frame_glitchwave', kind: 'frame', name: '글리치 웨이브', price: 2080, rarity: 'legendary', description: '핑크와 시안의 글리치 파형이 프레임 가장자리를 튀기며 흐르는 프레임.', accent: '#ff86e5' },
  { id: 'frame_cyber_shock', kind: 'frame', name: '사이버 쇼크', price: 2120, rarity: 'legendary', description: '전기 잔광과 디지털 쇼크 라인이 번쩍이는 프레임.', accent: '#74f7ff' },
  { id: 'frame_holo_bloom', kind: 'frame', name: '홀로 블룸', price: 2160, rarity: 'legendary', description: '홀로그램 꽃잎과 프리즘 광택이 맴도는 프레임.', accent: '#ffb6ef' },
  { id: 'frame_sunset_drive', kind: 'frame', name: '선셋 드라이브', price: 2020, rarity: 'epic', description: '주황빛 석양과 네온 선이 부드럽게 달리는 프레임.', accent: '#ffad70' },
  { id: 'frame_frost_arc', kind: 'frame', name: '프로스트 아크', price: 2140, rarity: 'legendary', description: '서리 결정과 푸른 냉기가 얇게 흐르는 프레임.', accent: '#c8e5ff' },
  { id: 'frame_comet_ring', kind: 'frame', name: '코멧 링', price: 2180, rarity: 'legendary', description: '혜성 꼬리가 궤도를 그리며 순환하는 프레임.', accent: '#9dddff' },
  { id: 'frame_velvet_rose', kind: 'frame', name: '벨벳 로즈', price: 2060, rarity: 'epic', description: '장미빛 벨벳 광택과 꽃잎 반짝임이 감도는 프레임.', accent: '#ff9ec8' },
  { id: 'frame_retro_scan', kind: 'frame', name: '레트로 스캔', price: 2000, rarity: 'epic', description: 'CRT 스캔라인과 픽셀 글로우가 퍼지는 프레임.', accent: '#8cffd8' },
  { id: 'frame_prayer_gold', kind: 'frame', name: '프레이어 골드', price: 2200, rarity: 'legendary', description: '금빛 성광과 유리창 빔이 내려앉는 성스러운 프레임.', accent: '#ffe19c' },
  { id: 'frame_quantum_cube', kind: 'frame', name: '퀀텀 큐브', price: 2240, rarity: 'legendary', description: '작은 큐브와 노이즈 조각이 차원처럼 점멸하는 프레임.', accent: '#a8a7ff' },
  { id: 'nickname_glitch_pink', kind: 'nickname', name: '핑크 글리치', price: 1450, rarity: 'legendary', description: '핑크·시안 분광 잔상이 튀는 글리치 닉네임 효과.', accent: '#ff8ddf' },
  { id: 'nickname_cyber_blue', kind: 'nickname', name: '사이버 블루', price: 1320, rarity: 'epic', description: '푸른 전류와 네온 잔광이 흐르는 닉네임 효과.', accent: '#7cecff' },
  { id: 'nickname_prism_pop', kind: 'nickname', name: '프리즘 팝', price: 1360, rarity: 'epic', description: '파스텔 프리즘 색이 빠르게 이동하는 반짝 닉네임 효과.', accent: '#f0a7ff' },
  { id: 'nickname_rose_gold', kind: 'nickname', name: '로즈 골드', price: 1490, rarity: 'legendary', description: '로즈 골드 하이라이트가 금속처럼 번쩍이는 닉네임 효과.', accent: '#ffb0bf' },
  { id: 'nickname_moon_dust', kind: 'nickname', name: '문 더스트', price: 1280, rarity: 'epic', description: '달빛 가루가 은은하게 스치듯 지나가는 닉네임 효과.', accent: '#dbe6ff' },
  { id: 'nickname_plasma', kind: 'nickname', name: '플라즈마 스파크', price: 1540, rarity: 'legendary', description: '보라색 플라즈마와 푸른 스파크가 튀는 닉네임 효과.', accent: '#ae92ff' },
  { id: 'nickname_auric_scan', kind: 'nickname', name: '오릭 스캔', price: 1510, rarity: 'legendary', description: '금빛 스캔 라인이 글자 위를 왕복하는 닉네임 효과.', accent: '#ffd785' },
  { id: 'nickname_mint_beam', kind: 'nickname', name: '민트 빔', price: 1220, rarity: 'epic', description: '민트빛 빔이 말끔하게 흐르는 상쾌한 닉네임 효과.', accent: '#9ff5dd' },
  { id: 'nickname_sticker_pop', kind: 'nickname', name: '스티커 팝', price: 1400, rarity: 'epic', description: '만화 스티커처럼 통통 튀는 그림자와 색감을 주는 닉네임 효과.', accent: '#ff8db5' },
  { id: 'nickname_quantum_noise', kind: 'nickname', name: '퀀텀 노이즈', price: 1620, rarity: 'legendary', description: '청보라 노이즈와 미세한 왜곡이 겹치는 닉네임 효과.', accent: '#93b7ff' }
];

export const PROFILE_COSMETIC_BY_ID = Object.fromEntries(PROFILE_COSMETICS.map((item) => [item.id, item])) as Record<string, ProfileCosmetic>;
