import type { CardDefinition } from './game-data';

/** v37: non-series TIME CORE cards. These are intentionally splashable across every series. */
export const V37_TIME_CORE_CARDS: CardDefinition[] = [
  { id:'v37_time_unit_01', name:'새벽잔영', subtitle:'TIME CORE · 여명', kind:'unit', rarity:'common', element:'solar', cost:1, attack:2, health:2, unitType:'spirit', target:'none', text:'여명에서만 소환 가능. 여명이 끝나면 소멸. 등장 시 카드 1장 드로우.', flavor:'첫 빛과 함께 나타나 다음 빛이 오기 전에 사라진다.', sigil:'☀', eclipseAffinity:'dawn', eclipseSummonPhases:['dawn'], eclipseLifespanPhases:['dawn'], eclipsePhaseModifiers:{dawn:{attack:2,health:0,label:'첫빛 폭증'}}, onSummon:{kind:'draw',amount:1}, temporalProfileName:'한시 생존' },
  { id:'v37_time_unit_02', name:'해돋이검', subtitle:'TIME CORE · 여명', kind:'unit', rarity:'rare', element:'solar', cost:2, attack:3, health:3, unitType:'vanguard', target:'none', text:'여명에서만 소환 가능. 여명이 끝나면 소멸. 여명 진입 시 아군 전체 +1/+1.', flavor:'검날은 해가 뜰 때만 완전한 형체를 가진다.', sigil:'☀', keywords:['charge'], eclipseAffinity:'dawn', eclipseSummonPhases:['dawn'], eclipseLifespanPhases:['dawn'], eclipsePhaseModifiers:{dawn:{attack:1,health:3,label:'새벽 성검'}}, eclipsePhasePulses:[{phase:'dawn',name:'첫빛진군',description:'여명 진입 또는 여명에서 등장 시 아군 전체 +1/+1.',effect:{kind:'mass_buff',attack:1,health:1}}], temporalProfileName:'첫빛 돌격' },
  { id:'v37_time_spell_01', name:'여명봉인', subtitle:'TIME CORE · 여명 전용', kind:'spell', rarity:'rare', element:'solar', cost:2, target:'none', text:'여명에서만 사용 가능. 아군 전체 보호막 3.', flavor:'동이 트는 순간만 열리는 방벽.', sigil:'☀', eclipseAffinity:'dawn', eclipsePlayPhases:['dawn'], effect:{kind:'phase_mass_shield',phase:'dawn',base:1,bonus:2} },
  { id:'v37_time_trap_01', name:'새벽역습', subtitle:'TIME CORE · 여명 함정', kind:'trap', rarity:'epic', element:'solar', cost:2, target:'none', text:'여명에만 발동. 상대의 직접 공격을 무효화하고 코어에 2 피해.', flavor:'첫 빛은 가장 긴 밤의 빈틈을 찌른다.', sigil:'☀', eclipseAffinity:'dawn', trapTrigger:'direct_attack', eclipseTriggerPhases:['dawn'], trapEffect:{kind:'negate_and_damage',amount:2} },

  { id:'v37_time_unit_03', name:'태양창', subtitle:'TIME CORE · 정점', kind:'unit', rarity:'common', element:'storm', cost:2, attack:4, health:2, unitType:'hunter', target:'none', text:'정점에서만 소환 가능. 정점이 끝나면 소멸. 정점에서는 추가 ATK +2.', flavor:'정오의 빛은 그림자를 가장 짧게 만든다.', sigil:'✦', keywords:['pierce'], eclipseAffinity:'zenith', eclipseSummonPhases:['zenith'], eclipseLifespanPhases:['zenith'], eclipsePhaseModifiers:{zenith:{attack:4,health:0,label:'극광 과열'}}, temporalProfileName:'정오 과열' },
  { id:'v37_time_unit_04', name:'정오거인', subtitle:'TIME CORE · 정점', kind:'unit', rarity:'epic', element:'neutral', cost:4, attack:7, health:6, unitType:'relic', target:'none', text:'정점에서만 소환 가능. 정점이 끝나면 소멸. 등장 시 상대 코어 2 피해.', flavor:'태양이 머리 위에 선 순간 거대한 그림자가 깨어난다.', sigil:'✦', eclipseAffinity:'zenith', eclipseSummonPhases:['zenith'], eclipseLifespanPhases:['zenith'], eclipsePhaseModifiers:{zenith:{attack:1,health:3,label:'정오 중력'}}, onSummon:{kind:'damage_core',amount:2}, temporalProfileName:'정점 현현' },
  { id:'v37_time_spell_02', name:'천정선고', subtitle:'TIME CORE · 정점 전용', kind:'spell', rarity:'epic', element:'storm', cost:4, target:'none', text:'정점에서만 사용 가능. 모든 적 유닛에 5 피해.', flavor:'하늘의 가장 높은 곳에서 판결이 떨어진다.', sigil:'✦', eclipseAffinity:'zenith', eclipsePlayPhases:['zenith'], effect:{kind:'phase_aoe_enemy',phase:'zenith',base:2,bonus:3} },
  { id:'v37_time_trap_02', name:'정오반사', subtitle:'TIME CORE · 정점 함정', kind:'trap', rarity:'rare', element:'neutral', cost:2, target:'none', text:'정점에만 발동. 상대 주문을 무효화.', flavor:'정점의 빛은 모든 술식을 되비춘다.', sigil:'✦', eclipseAffinity:'zenith', trapTrigger:'spell_played', eclipseTriggerPhases:['zenith'], trapEffect:{kind:'negate'} },

  { id:'v37_time_unit_05', name:'석양매', subtitle:'TIME CORE · 황혼', kind:'unit', rarity:'common', element:'verdant', cost:2, attack:4, health:2, unitType:'hunter', target:'none', text:'황혼에서만 소환 가능. 황혼이 끝나면 소멸. 소환 즉시 공격 가능.', flavor:'해가 지는 속도보다 빠르게 목표를 낚아챈다.', sigil:'◐', keywords:['charge'], eclipseAffinity:'dusk', eclipseSummonPhases:['dusk'], eclipseLifespanPhases:['dusk'], eclipsePhaseModifiers:{dusk:{attack:3,health:0,label:'낙일 급강하'}}, temporalProfileName:'낙일 질주' },
  { id:'v37_time_unit_06', name:'낙일기사', subtitle:'TIME CORE · 황혼', kind:'unit', rarity:'rare', element:'lunar', cost:3, attack:3, health:6, unitType:'vanguard', target:'none', text:'황혼에서만 소환 가능. 심야가 되면 소멸. 황혼 진입 시 아군 전체 보호막 2.', flavor:'마지막 햇빛이 사라질 때까지 후퇴하지 않는다.', sigil:'◐', keywords:['guard'], eclipseAffinity:'dusk', eclipseSummonPhases:['dusk'], eclipseVanishPhases:['midnight'], eclipsePhaseModifiers:{dusk:{attack:0,health:4,label:'황혼 철벽'}}, eclipsePhasePulses:[{phase:'dusk',name:'낙일방진',description:'황혼 진입 또는 황혼에서 등장 시 아군 전체 보호막 2.',effect:{kind:'mass_shield',amount:2}}], temporalProfileName:'황혼 수호' },
  { id:'v37_time_spell_03', name:'황혼봉쇄', subtitle:'TIME CORE · 황혼 전용', kind:'spell', rarity:'rare', element:'lunar', cost:2, target:'none', text:'황혼에서만 사용 가능. 현재 시간을 2턴 동안 고정.', flavor:'저무는 찰나를 붙잡아 전장을 길게 늘인다.', sigil:'◐', eclipseAffinity:'dusk', eclipsePlayPhases:['dusk'], effect:{kind:'phase_lock',turns:2} },
  { id:'v37_time_trap_03', name:'낙조매복', subtitle:'TIME CORE · 황혼 함정', kind:'trap', rarity:'epic', element:'verdant', cost:2, target:'none', text:'황혼에만 발동. 상대 유닛 소환을 무효화.', flavor:'빛과 어둠이 섞이는 순간 가장 완벽한 매복이 열린다.', sigil:'◐', eclipseAffinity:'dusk', trapTrigger:'unit_summoned', eclipseTriggerPhases:['dusk'], trapEffect:{kind:'negate'} },

  { id:'v37_time_unit_07', name:'자정마녀', subtitle:'TIME CORE · 심야', kind:'unit', rarity:'rare', element:'void', cost:3, attack:3, health:4, unitType:'oracle', target:'none', text:'심야에서만 소환 가능. 심야가 끝나면 소멸. 심야 진입 시 상대 ENERGY 1을 빼앗음.', flavor:'시계가 자정을 가리킬 때만 그녀의 이름이 들린다.', sigil:'☾', eclipseAffinity:'midnight', eclipseSummonPhases:['midnight'], eclipseLifespanPhases:['midnight'], eclipsePhaseModifiers:{midnight:{attack:2,health:1,label:'자정 주술'}}, eclipsePhasePulses:[{phase:'midnight',name:'자정징수',description:'심야 진입 또는 심야에서 등장 시 상대 ENERGY 1을 빼앗습니다.',effect:{kind:'steal_energy',amount:1}}], temporalProfileName:'자정 징수' },
  { id:'v37_time_unit_08', name:'밤시계', subtitle:'TIME CORE · 심야', kind:'unit', rarity:'common', element:'neutral', cost:2, attack:1, health:5, unitType:'relic', target:'none', text:'심야와 개기일식에서만 소환 가능. 여명이 되면 소멸. 심야 진입 시 카드 1장 드로우.', flavor:'밤이 이어지는 동안만 멈추지 않는 시계.', sigil:'☾', keywords:['guard'], eclipseAffinity:'midnight', eclipseSummonPhases:['midnight','eclipse'], eclipseVanishPhases:['dawn'], eclipsePhaseModifiers:{midnight:{attack:0,health:5,label:'심야 요새'},eclipse:{attack:2,health:2,label:'흑야 연장'}}, eclipsePhasePulses:[{phase:'midnight',name:'야간기록',description:'심야 진입 또는 심야에서 등장 시 카드 1장 드로우.',effect:{kind:'draw',amount:1}}], temporalProfileName:'야간 기록' },
  { id:'v37_time_spell_04', name:'심야문', subtitle:'TIME CORE · 심야 전용', kind:'spell', rarity:'epic', element:'void', cost:3, target:'none', text:'심야에서만 사용 가능. 5/5 밤의 사자를 소환.', flavor:'문은 낮에는 벽일 뿐이다.', sigil:'☾', eclipseAffinity:'midnight', eclipsePlayPhases:['midnight'], effect:{kind:'phase_summon_token',phase:'midnight',attack:2,health:2,bonusAttack:3,bonusHealth:3,name:'밤의사자'} },
  { id:'v37_time_trap_04', name:'자정절단', subtitle:'TIME CORE · 심야 함정', kind:'trap', rarity:'rare', element:'void', cost:2, target:'none', text:'심야에만 발동. 상대의 특수 소환을 무효화하고 코어에 1 피해.', flavor:'자정의 칼날은 소환문이 닫히는 순간을 벤다.', sigil:'☾', eclipseAffinity:'midnight', trapTrigger:'special_summoned', eclipseTriggerPhases:['midnight'], trapEffect:{kind:'negate_and_damage',amount:1} },

  { id:'v37_time_unit_09', name:'흑일용', subtitle:'TIME CORE · 개기일식', kind:'unit', rarity:'legendary', element:'void', cost:7, attack:9, health:7, unitType:'spirit', target:'none', text:'개기일식에서만 특수 소환 가능. 개기일식이 끝나면 소멸. 등장 시 상대 코어 3 피해.', flavor:'태양이 지워진 단 한 순간, 검은 용이 하늘을 차지한다.', sigil:'◉', eclipseAffinity:'eclipse', eclipseSummonPhases:['eclipse'], eclipseLifespanPhases:['eclipse'], eclipsePhaseModifiers:{eclipse:{attack:2,health:1,label:'흑일 지배'}}, summonMode:'legendary', legendarySummonRule:{name:'흑일강림',label:'개기일식 + 내 묘지 5장 이상',release:'none',graveyardMin:5}, onSummon:{kind:'damage_core',amount:3}, temporalProfileName:'일식 강림' },
  { id:'v37_time_unit_10', name:'식광사제', subtitle:'TIME CORE · 개기일식', kind:'unit', rarity:'epic', element:'lunar', cost:4, attack:4, health:5, unitType:'oracle', target:'none', text:'개기일식에서만 소환 가능. 여명이 되면 소멸. 개기일식 진입 시 묘지 카드 1장 회수.', flavor:'빛이 사라진 동안 잊힌 것의 이름을 다시 부른다.', sigil:'◉', eclipseAffinity:'eclipse', eclipseSummonPhases:['eclipse'], eclipseVanishPhases:['dawn'], eclipsePhaseModifiers:{eclipse:{attack:1,health:3,label:'식광 성역'}}, eclipsePhasePulses:[{phase:'eclipse',name:'흑광회수',description:'개기일식 진입 또는 개기일식에서 등장 시 묘지 카드 1장 회수.',effect:{kind:'recover_grave',amount:1}}], temporalProfileName:'흑광 회수' },
  { id:'v37_time_spell_05', name:'일식종말', subtitle:'TIME CORE · 개기일식 전용', kind:'spell', rarity:'legendary', element:'void', cost:6, target:'none', text:'개기일식에서만 사용 가능. 모든 적 유닛에 5 피해.', flavor:'모든 빛이 가려진 뒤 남는 것은 전장의 결론뿐이다.', sigil:'◉', eclipseAffinity:'eclipse', eclipsePlayPhases:['eclipse'], effect:{kind:'phase_aoe_enemy',phase:'eclipse',base:2,bonus:3} },
  { id:'v37_time_trap_05', name:'식광반전', subtitle:'TIME CORE · 개기일식 함정', kind:'trap', rarity:'legendary', element:'void', cost:3, target:'none', text:'개기일식에만 발동. 상대의 융합 소환을 무효화하고 코어에 3 피해.', flavor:'완성되던 형체가 일식 속에서 거꾸로 무너진다.', sigil:'◉', eclipseAffinity:'eclipse', trapTrigger:'fusion_summoned', eclipseTriggerPhases:['eclipse'], trapEffect:{kind:'negate_and_damage',amount:3} },

  { id:'v37_time_spell_06', name:'시침가속', subtitle:'TIME CORE · 시간 조작', kind:'spell', rarity:'common', element:'neutral', cost:1, target:'none', text:'시간을 앞으로 1단계 이동.', flavor:'한 칸의 시침이 한 판의 승패를 바꾼다.', sigil:'⌚', effect:{kind:'phase_shift',steps:1} },
  { id:'v37_time_spell_07', name:'역행초침', subtitle:'TIME CORE · 시간 조작', kind:'spell', rarity:'rare', element:'neutral', cost:2, target:'none', text:'실제 직전 시간대로 되감기.', flavor:'이미 지나간 순간을 다시 전장 위에 올린다.', sigil:'⌚', effect:{kind:'phase_rewind',steps:1} },
  { id:'v37_time_spell_08', name:'시각고정', subtitle:'TIME CORE · 시간 조작', kind:'spell', rarity:'rare', element:'neutral', cost:2, target:'none', text:'현재 시간을 2턴 동안 고정.', flavor:'전장 전체가 한 장의 사진처럼 멈춘다.', sigil:'⌚', effect:{kind:'phase_lock',turns:2} },
  { id:'v37_time_spell_09', name:'운명교차', subtitle:'TIME CORE · 시간 조작', kind:'spell', rarity:'epic', element:'neutral', cost:3, target:'none', text:'시간을 앞으로 2단계 이동.', flavor:'기다리는 대신 미래를 끌어당긴다.', sigil:'⌚', effect:{kind:'phase_shift',steps:2} },
  { id:'v37_time_spell_10', name:'끝없는밤', subtitle:'TIME CORE · 시간 조작', kind:'spell', rarity:'legendary', element:'lunar', cost:5, target:'none', text:'시간을 즉시 심야로 변경.', flavor:'밤이 끝나지 않는다면 밤의 카드도 끝나지 않는다.', sigil:'☾', effect:{kind:'phase_set',phase:'midnight'} },

  { id:'v37_time_spell_11', name:'시각부정', subtitle:'TIME CORE · 시간 카운터', kind:'spell', rarity:'rare', element:'neutral', cost:2, target:'none', text:'상대가 직전 턴에 바꾼 시간이 아직 유지 중일 때만 사용. 그 변경 직전 시간으로 되돌린다.', flavor:'바뀐 것은 시간이 아니라 관측 결과였다고 선언한다.', sigil:'↶', effect:{kind:'phase_counter_enemy'} },
  { id:'v37_time_spell_12', name:'역전시계', subtitle:'TIME CORE · 시간 카운터', kind:'spell', rarity:'epic', element:'neutral', cost:3, target:'none', text:'상대가 직전 턴에 바꾼 시간을 되돌리고, 되돌린 시간을 1턴 고정한다.', flavor:'되감긴 시침은 같은 실수를 두 번 허락하지 않는다.', sigil:'↺', effect:{kind:'phase_counter_enemy',lockTurns:1} },
  { id:'v37_time_spell_13', name:'시간탈취', subtitle:'TIME CORE · 시간 카운터', kind:'spell', rarity:'epic', element:'lunar', cost:3, target:'none', text:'상대가 직전 턴에 바꾼 시간을 되돌리고 상대 ENERGY 1을 빼앗는다.', flavor:'상대가 훔친 한 순간을 되찾아 내 동력으로 바꾼다.', sigil:'⌛', effect:{kind:'phase_counter_enemy',stealEnergy:1} },
  { id:'v37_time_spell_14', name:'인과반전', subtitle:'TIME CORE · 시간 카운터', kind:'spell', rarity:'legendary', element:'void', cost:4, target:'none', text:'상대가 직전 턴에 바꾼 시간을 되돌린 뒤 1단계 더 역행하고 카드 1장을 뽑는다.', flavor:'결과를 지우는 대신 원인보다 먼저 도착한다.', sigil:'∞', effect:{kind:'phase_counter_enemy',extraBackSteps:1,draw:1} },
];
