import type { CardDefinition } from './game-data';

export const V41_PREMIUM_TIME_CARDS: CardDefinition[] = [
  {
    id: 'v41_premium_zenith_king',
    name: '정점의 왕',
    subtitle: 'PREMIUM TIME · 정점의 절대자',
    kind: 'unit',
    rarity: 'legendary',
    element: 'storm',
    cost: 8,
    attack: 11,
    health: 12,
    unitType: 'vanguard',
    target: 'none',
    keywords: ['corestrike', 'guard', 'charge', 'pierce'],
    text: '【고유 특성 · 천정 왕권】 등장 시 현재 시간을 정점으로 설정하고 2턴 동안 고정한다. 아군 전체 +2/+2 후 즉시 공격 준비. 정점 진입 또는 정점에서 등장 시 왕의 호령으로 아군 전체 준비 완료, 정오 판결로 상대 코어 5 피해, 태양세로 상대 ENERGY 1 흡수, 4/4 「천정 근위」 1체를 소환한다.',
    uniqueTrait: { name: '천정 왕권', description: '태양이 가장 높은 순간을 왕의 영토로 선포한다. 정점을 고정하고 군세를 즉시 전투 태세로 만든다.' },
    flavor: '한낮의 절정에 도달한 왕은 전장의 모든 시계를 자신에게 맞춘다.',
    sigil: '☼',
    summonMode: 'legendary',
    legendarySummonRule: { name: '절정 강림', label: '아군 유닛 2장을 릴리스하고 소환', release: 'all', minimumAllies: 2 },
    onSummon: { kind: 'phase_set', phase: 'zenith' },
    eclipseAffinity: 'zenith',
    eclipseSummonPhases: ['zenith', 'eclipse'],
    eclipseVanishPhases: ['midnight'],
    eclipsePhaseModifiers: { zenith: { attack: 4, health: 3, label: '천정 왕권' }, eclipse: { attack: 1, health: 2, label: '식광 잔열' } },
    eclipsePhasePulses: [
      { phase: 'zenith', name: '왕의 호령', description: '정점 진입 또는 정점에서 등장 시 아군 전체를 준비 완료한다.', effect: { kind: 'ready_all' } },
      { phase: 'zenith', name: '정오 판결', description: '정점 진입 또는 정점에서 등장 시 상대 코어에 5 피해.', effect: { kind: 'damage_core', amount: 5 } },
      { phase: 'zenith', name: '태양세', description: '정점 진입 또는 정점에서 등장 시 상대 ENERGY 1을 흡수한다.', effect: { kind: 'steal_energy', amount: 1 } },
      { phase: 'zenith', name: '천정 근위', description: '정점 진입 또는 정점에서 등장 시 4/4 「천정 근위」 1체를 소환한다.', effect: { kind: 'summon_token', attack: 4, health: 4, name: '천정 근위' } },
    ],
    temporalProfileName: '정점 군림',
  },
  {
    id: 'v41_premium_dawn_lord',
    name: '여명의 지배자',
    subtitle: 'PREMIUM TIME · 첫빛의 군주',
    kind: 'unit',
    rarity: 'legendary',
    element: 'solar',
    cost: 7,
    attack: 10,
    health: 11,
    unitType: 'oracle',
    target: 'none',
    keywords: ['lifesteal', 'charge', 'guard'],
    text: '【고유 특성 · 첫빛의 윤회】 등장 시 시간을 여명으로 되돌리고 카드 1장을 드로우, ENERGY 최대치 +1, 코어 6 회복, 묘지 유닛 1장 회수. 여명 진입 또는 여명에서 등장 시 묘지 최고 비용 유닛 1체를 체력 60%로 되살리고, 아군 전체 체력 3 회복, 아군 전체 공격 준비, 카드 1장 드로우.',
    uniqueTrait: { name: '첫빛의 윤회', description: '첫 햇빛이 패배한 전열을 다시 깨운다. 회복과 부활에 특화된 여명 전용 고유 능력.' },
    flavor: '태양이 떠오르는 순간, 패배와 상처는 전부 어제로 밀려난다.',
    sigil: '✧',
    summonMode: 'legendary',
    legendarySummonRule: { name: '찬란 회귀', label: '내 코어 24 이하 또는 묘지 5장 이상', release: 'none', coreAtMost: 24, graveyardMin: 5 },
    onSummon: { kind: 'phase_set', phase: 'dawn' },
    eclipseAffinity: 'dawn',
    eclipseSummonPhases: ['dawn', 'midnight', 'eclipse'],
    eclipsePhaseModifiers: { dawn: { attack: 4, health: 4, label: '첫빛 재생' }, midnight: { attack: -1, health: 2, label: '밤샘 기도' } },
    eclipsePhasePulses: [
      { phase: 'dawn', name: '새벽 재기', description: '여명 진입 또는 여명에서 등장 시 묘지 최고 비용 유닛 1체를 체력 60%로 부활시킨다.', effect: { kind: 'revive_best_grave', healthRatio: 0.6, ready: false } },
      { phase: 'dawn', name: '첫빛 치유', description: '여명 진입 또는 여명에서 등장 시 아군 전체 체력 3 회복.', effect: { kind: 'heal_allies', amount: 3 } },
      { phase: 'dawn', name: '일출 행진', description: '여명 진입 또는 여명에서 등장 시 아군 전체를 공격 준비 상태로 만든다.', effect: { kind: 'ready_all' } },
      { phase: 'dawn', name: '여명의 계시', description: '여명 진입 또는 여명에서 등장 시 카드 1장을 드로우한다.', effect: { kind: 'draw', amount: 1 } },
    ],
    temporalProfileName: '여명 지배',
  },
  {
    id: 'v41_premium_eclipse_conductor',
    name: '개기일식의 조율자',
    subtitle: 'PREMIUM TIME · 흑광의 지휘자',
    kind: 'unit',
    rarity: 'legendary',
    element: 'void',
    cost: 8,
    attack: 11,
    health: 12,
    unitType: 'spirit',
    target: 'none',
    keywords: ['pierce', 'execute', 'charge', 'guard'],
    text: '【고유 특성 · 흑광 대지휘】 등장 시 개기일식으로 시간을 설정하고 2턴 고정. 가장 강한 적을 리콜하고 상대 묘지 1장 소멸, 상대 ENERGY 1 흡수. 개기일식 진입 또는 등장 시 저음부 귀환으로 묘지 최고 비용 유닛 1체를 체력 80%로 부활, 무음 지휘로 가장 강한 적의 강화/보호막 초기화, 종결 화음으로 상대 코어 4 피해, 4/4 「흑광 악장」 소환.',
    uniqueTrait: { name: '흑광 대지휘', description: '전장을 하나의 악보로 보고 적의 템포를 끊고, 묘지의 아군을 다시 무대에 올리는 지휘형 고유 능력.' },
    flavor: '모든 리듬을 멈춘 뒤, 그는 일식의 박자로만 전장을 다시 움직인다.',
    sigil: '◉',
    summonMode: 'legendary',
    legendarySummonRule: { name: '흑광 조율', label: '묘지 6장 이상 + 아군 유닛 1장 릴리스', release: 'all', minimumAllies: 1, graveyardMin: 6 },
    onSummon: { kind: 'phase_set', phase: 'eclipse' },
    eclipseAffinity: 'eclipse',
    eclipseSummonPhases: ['eclipse'],
    eclipseLifespanPhases: ['eclipse'],
    eclipsePhaseModifiers: { eclipse: { attack: 3, health: 3, label: '흑광 총주' } },
    eclipsePhasePulses: [
      { phase: 'eclipse', name: '저음부 귀환', description: '개기일식 진입 또는 등장 시 내 묘지 최고 비용 유닛 1체를 체력 80%로 부활시킨다.', effect: { kind: 'revive_best_grave', healthRatio: 0.8, ready: false } },
      { phase: 'eclipse', name: '무음 지휘', description: '개기일식 진입 또는 등장 시 가장 강한 적 유닛의 강화 수치와 보호막을 초기화한다.', effect: { kind: 'reset_strongest_enemy' } },
      { phase: 'eclipse', name: '종결 화음', description: '개기일식 진입 또는 등장 시 상대 코어에 4 피해.', effect: { kind: 'damage_core', amount: 4 } },
      { phase: 'eclipse', name: '흑광 악장', description: '개기일식 진입 또는 등장 시 4/4 「흑광 악장」 1체를 소환한다.', effect: { kind: 'summon_token', attack: 4, health: 4, name: '흑광 악장' } },
    ],
    temporalProfileName: '식광 조율',
  },
  {
    id: 'v44_premium_twilight_knight',
    name: '황혼의 기사',
    subtitle: 'PREMIUM TIME · 저녁별의 맹세',
    kind: 'unit',
    rarity: 'legendary',
    element: 'lunar',
    cost: 7,
    attack: 10,
    health: 12,
    unitType: 'vanguard',
    target: 'none',
    keywords: ['guard', 'pierce', 'sweep', 'charge'],
    text: '【고유 특성 · 경계의 맹세】 등장 시 시간을 황혼으로 설정하고 카드 1장 드로우, 자신에게 보호막 3. 황혼 진입 또는 황혼에서 등장 시 코어 격차를 최대 5까지 보정하고, 아군 전체 보호막 +2, 상대 코어 2를 흡수하며 현재 ATK+DEF가 9 이하인 가장 약한 적 1체를 붕괴시킨다. 황혼에서는 +4/+4.',
    uniqueTrait: { name: '경계의 맹세', description: '낮과 밤의 경계에서 우세한 쪽을 견제하고 불리한 쪽을 끌어올리는 결투형 고유 능력.' },
    flavor: '낮도 밤도 아닌 순간, 그는 두 세계의 검을 동시에 뽑는다.',
    sigil: '☽',
    summonMode: 'legendary',
    legendarySummonRule: { name: '황혼 서약', label: '내 묘지에 카드가 5장 이상일 때', release: 'none', graveyardMin: 5 },
    onSummon: { kind: 'phase_set', phase: 'dusk' },
    eclipseAffinity: 'dusk',
    eclipseSummonPhases: ['dusk', 'eclipse'],
    eclipsePhaseModifiers: { dusk: { attack: 4, health: 4, label: '황혼 기사도' }, eclipse: { attack: 1, health: 2, label: '식광 잔영' }, dawn: { attack: -1, health: 1, label: '새벽의 후퇴' } },
    eclipsePhasePulses: [
      { phase: 'dusk', name: '경계의 저울', description: '황혼 진입 또는 황혼에서 등장 시 코어 격차를 최대 5까지 보정한다.', effect: { kind: 'core_equalize', cap: 5 } },
      { phase: 'dusk', name: '저녁별 방진', description: '황혼 진입 또는 황혼에서 등장 시 아군 전체 보호막 +2.', effect: { kind: 'mass_shield', amount: 2 } },
      { phase: 'dusk', name: '저무는 칼날', description: '황혼 진입 또는 황혼에서 등장 시 상대 코어 2를 흡수한다.', effect: { kind: 'drain_core', amount: 2 } },
      { phase: 'dusk', name: '박명 결투', description: '황혼 진입 또는 황혼에서 등장 시 현재 ATK+DEF 9 이하인 가장 약한 적 1체를 붕괴시킨다.', effect: { kind: 'collapse_weakest_enemy', maxPower: 9 } },
    ],
    temporalProfileName: '황혼 기사도',
  },
  {
    id: 'v41_premium_midnight_silence',
    name: '심야의 침묵',
    subtitle: 'PREMIUM TIME · 심야 초월 주문',
    kind: 'spell',
    rarity: 'legendary',
    element: 'lunar',
    cost: 6,
    target: 'none',
    text: '【고유 주문 · 절대 무음령】 현재 시간을 심야로 설정하고 2턴 동안 고정한다. 모든 적 유닛을 1턴 동결하고 상대 손패의 최고 비용 카드 1장을 버리게 한 뒤 상대 묘지 2장을 소멸시킨다. 마지막으로 카드 1장을 드로우한다. 직접 피해보다 상대의 행동 선택지를 지우는 심야 전용 주문.',
    uniqueTrait: { name: '절대 무음령', description: '공격·손패·묘지의 목소리를 차례로 끊어 상대의 다음 행동 폭을 강제로 줄인다.' },
    flavor: '모든 말과 모든 검이 멎은 뒤 남는 것은 자정의 한 줄 결론뿐이다.',
    sigil: '☾',
    eclipseAffinity: 'midnight',
    effect: { kind: 'phase_set', phase: 'midnight' },
  },
];
