import type { CardDefinition } from './game-data';

export const V41_PREMIUM_TIME_CARDS: CardDefinition[] = [
  {
    id: 'v41_premium_zenith_king',
    name: '정점의 왕',
    subtitle: 'PREMIUM TIME · 정점의 절대자',
    kind: 'unit',
    rarity: 'legendary',
    element: 'storm',
    cost: 8,
    attack: 10,
    health: 10,
    unitType: 'vanguard',
    target: 'none',
    keywords: ['corestrike', 'guard'],
    text: '등장 시 현재 시간을 정점으로 설정하고 2턴 동안 고정. 아군 전체에게 +2/+2와 보호막 4를 부여한다. 정점 진입 또는 정점에서 등장 시 아군 전체 준비 완료 및 상대 코어 4 피해.',
    flavor: '한낮의 절정에 도달한 왕은 전장의 모든 시계를 자신에게 맞춘다.',
    sigil: '☼',
    summonMode: 'legendary',
    legendarySummonRule: { name: '절정 강림', label: '아군 유닛 2장을 릴리스하고 소환', release: 'all', minimumAllies: 2 },
    onSummon: { kind: 'phase_set', phase: 'zenith' },
    eclipseAffinity: 'zenith',
    eclipseSummonPhases: ['zenith', 'eclipse'],
    eclipseVanishPhases: ['midnight'],
    eclipsePhaseModifiers: { zenith: { attack: 2, health: 4, label: '절정 군림' }, eclipse: { attack: 1, health: 2, label: '식광 잔열' } },
    eclipsePhasePulses: [
      { phase: 'zenith', name: '천정 즉위', description: '정점 진입 또는 정점에서 등장 시 아군 전체를 준비 완료하고 +2/+2 부여.', effect: { kind: 'ready_all' } },
      { phase: 'zenith', name: '정오 압정', description: '정점 진입 또는 정점에서 등장 시 상대 코어에 4 피해.', effect: { kind: 'damage_core', amount: 4 } },
    ],
    temporalProfileName: '정점 군림',
  },
  {
    id: 'v41_premium_dawn_lord',
    name: '여명의 지배자',
    subtitle: 'PREMIUM TIME · 첫빛의 군주',
    kind: 'unit',
    rarity: 'legendary',
    element: 'solar',
    cost: 7,
    attack: 8,
    health: 9,
    unitType: 'oracle',
    target: 'none',
    keywords: ['lifesteal', 'charge'],
    text: '등장 시 여명으로 시간을 되돌리고 카드 2장을 드로우, ENERGY 최대치를 1 증가시킨다. 여명 진입 또는 여명에서 등장 시 아군 전체 +2/+3, 코어 4 회복, 상대 가장 강한 적 1체를 동결 1턴.',
    flavor: '태양이 떠오르는 순간, 패배와 상처는 전부 어제로 밀려난다.',
    sigil: '✧',
    summonMode: 'legendary',
    legendarySummonRule: { name: '찬란 회귀', label: '내 코어 24 이하 또는 묘지 5장 이상', release: 'none', coreAtMost: 24, graveyardMin: 5 },
    onSummon: { kind: 'phase_set', phase: 'dawn' },
    eclipseAffinity: 'dawn',
    eclipseSummonPhases: ['dawn', 'midnight', 'eclipse'],
    eclipsePhaseModifiers: { dawn: { attack: 3, health: 3, label: '첫빛 재생' }, midnight: { attack: -1, health: 2, label: '밤샘 기도' } },
    eclipsePhasePulses: [
      { phase: 'dawn', name: '새벽 칙령', description: '여명 진입 또는 여명에서 등장 시 아군 전체 +2/+3.', effect: { kind: 'mass_buff', attack: 2, health: 3 } },
      { phase: 'dawn', name: '광휘 치유', description: '여명 진입 또는 여명에서 등장 시 내 코어를 4 회복.', effect: { kind: 'heal_core', amount: 4 } },
      { phase: 'dawn', name: '빛의 정지', description: '여명 진입 또는 여명에서 등장 시 가장 강한 적 1체를 1턴 동결.', effect: { kind: 'freeze_strongest', turns: 1 } },
    ],
    temporalProfileName: '여명 지배',
  },
  {
    id: 'v41_premium_eclipse_conductor',
    name: '개기일식의 조율자',
    subtitle: 'PREMIUM TIME · 흑광의 지휘자',
    kind: 'unit',
    rarity: 'legendary',
    element: 'void',
    cost: 8,
    attack: 9,
    health: 9,
    unitType: 'spirit',
    target: 'none',
    keywords: ['pierce', 'execute'],
    text: '등장 시 개기일식으로 시간을 설정하고 2턴 고정. 상대 필드의 가장 강한 유닛을 리콜하고 상대 묘지 2장을 제외한다. 개기일식 진입 또는 개기일식에서 등장 시 상대 코어 5 피해, 내 묘지 최고 비용 유닛 1체를 체력 70%로 부활.',
    flavor: '모든 리듬을 멈춘 뒤, 그는 일식의 박자로만 전장을 다시 움직인다.',
    sigil: '◉',
    summonMode: 'legendary',
    legendarySummonRule: { name: '흑광 조율', label: '묘지 6장 이상 + 아군 유닛 1장 릴리스', release: 'all', minimumAllies: 1, graveyardMin: 6 },
    onSummon: { kind: 'phase_set', phase: 'eclipse' },
    eclipseAffinity: 'eclipse',
    eclipseSummonPhases: ['eclipse'],
    eclipseLifespanPhases: ['eclipse'],
    eclipsePhaseModifiers: { eclipse: { attack: 3, health: 3, label: '흑광 총주' } },
    eclipsePhasePulses: [
      { phase: 'eclipse', name: '식광 붕락', description: '개기일식 진입 또는 개기일식에서 등장 시 상대 코어에 5 피해.', effect: { kind: 'damage_core', amount: 5 } },
      { phase: 'eclipse', name: '어둠 회수', description: '개기일식 진입 또는 개기일식에서 등장 시 내 묘지 최고 비용 유닛 1체를 부활.', effect: { kind: 'revive_best_grave', healthRatio: 0.7, ready: true } },
      { phase: 'eclipse', name: '흑일 소거', description: '개기일식 진입 또는 개기일식에서 등장 시 가장 강한 적 유닛을 패로 되돌린다.', effect: { kind: 'recall_strongest_enemy' } },
    ],
    temporalProfileName: '식광 조율',
  },
  {
    id: 'v41_premium_midnight_silence',
    name: '심야의 침묵',
    subtitle: 'PREMIUM TIME · 심야 초월 주문',
    kind: 'spell',
    rarity: 'legendary',
    element: 'lunar',
    cost: 6,
    target: 'none',
    text: '현재 시간을 심야로 설정하고 2턴 동안 고정. 모든 적 유닛을 1턴 동결하고 상대 손패의 최고 비용 카드 2장을 버리게 한다. 심야라면 추가로 상대 코어 6 피해, 내가 카드 2장 드로우, ENERGY 2 획득.',
    flavor: '모든 말과 모든 검이 멎은 뒤 남는 것은 자정의 한 줄 결론뿐이다.',
    sigil: '☾',
    eclipseAffinity: 'midnight',
    effect: { kind: 'phase_set', phase: 'midnight' },
  },
];
