import type { CardDefinition } from './game-data';

export const V41_PREMIUM_TIME_CARDS: CardDefinition[] = [
  {
    id: 'v41_premium_zenith_king',
    name: '태양전차 라그나크',
    subtitle: 'PREMIUM TIME · 정오를 질주하는 태양전차',
    kind: 'unit',
    rarity: 'legendary',
    element: 'storm',
    cost: 8,
    attack: 11,
    health: 12,
    unitType: 'vanguard',
    target: 'none',
    keywords: ['corestrike', 'guard', 'charge', 'pierce'],
    text: '【고유 특성 · 천정 왕권】 정점 전용 전설 캐릭터. 【등장】 현재 시간을 정점으로 설정하고 2턴 동안 고정한다. 아군 전체 +2/+2 후 즉시 공격 준비. 【정점 전용 발동】 아군 전체를 준비 완료하고, 상대 코어에 5 피해를 주고, 상대 ENERGY 1을 흡수하며, 4/4 「천정 근위」 1체를 소환한다.',
    uniqueTrait: { name: '태양기관 폭주', description: '정점에서 태양기관을 과부하시켜 전열 전체를 전진시키는 기갑형 고유 특성이다.' },
    flavor: '정오의 태양을 엔진으로 삼은 전차가 하늘의 궤도를 짓밟으며 돌진한다.',
    sigil: '⚙',
    summonMode: 'legendary',
    legendarySummonRule: { name: '태양궤도 진입', label: '아군 유닛 2장을 릴리스하고 소환', release: 'all', minimumAllies: 2 },
    onSummon: { kind: 'phase_set', phase: 'zenith' },
    eclipseAffinity: 'zenith',
    eclipseSummonPhases: ['zenith'],
    eclipseVanishPhases: ['midnight'],
    eclipsePhaseModifiers: { zenith: { attack: 4, health: 3, label: '천정 왕권' }, eclipse: { attack: 1, health: 2, label: '식광 잔열' } },
    eclipsePhasePulses: [
      { phase: 'zenith', name: '왕의 호령', description: '정점 진입 또는 정점에서 등장 시 아군 전체를 준비 완료한다.', effect: { kind: 'ready_all' } },
      { phase: 'zenith', name: '정오 판결', description: '정점 진입 또는 정점에서 등장 시 상대 코어에 5 피해.', effect: { kind: 'damage_core', amount: 5 } },
      { phase: 'zenith', name: '태양세', description: '정점 진입 또는 정점에서 등장 시 상대 ENERGY 1을 흡수한다.', effect: { kind: 'steal_energy', amount: 1 } },
      { phase: 'zenith', name: '천정 근위', description: '정점 진입 또는 정점에서 등장 시 4/4 「천정 근위」 1체를 소환한다.', effect: { kind: 'summon_token', attack: 4, health: 4, name: '천정 근위' } },
    ],
    temporalProfileName: '정점 군림',
  },
  {
    id: 'v41_premium_dawn_lord',
    name: '여명성녀 아우렐리아',
    subtitle: 'PREMIUM TIME · 첫빛을 되돌리는 성녀',
    kind: 'unit',
    rarity: 'legendary',
    element: 'solar',
    cost: 7,
    attack: 10,
    health: 11,
    unitType: 'oracle',
    target: 'none',
    keywords: ['lifesteal', 'charge', 'guard'],
    text: '【고유 특성 · 첫빛의 윤회】 여명 전용 전설 캐릭터. 【등장】 시간을 여명으로 되돌리고 카드 1장을 드로우, ENERGY 최대치 +1, 코어 6 회복, 묘지의 캐릭터 1장을 회수한다. 【여명 전용 발동】 묘지의 최고 비용 캐릭터 1체를 체력 60%로 부활시키고, 아군 전체 체력 3을 회복시키며, 아군 전체를 공격 준비 상태로 만들고, 카드 1장을 드로우한다.',
    uniqueTrait: { name: '첫빛의 성흔', description: '여명의 첫빛으로 쓰러진 아군을 다시 일으키는 재생형 고유 특성이다.' },
    flavor: '첫 새벽빛이 성흔에 닿는 순간, 쓰러졌던 이름들이 다시 호명된다.',
    sigil: '✦',
    summonMode: 'legendary',
    legendarySummonRule: { name: '찬란 회귀', label: '내 코어 24 이하 또는 묘지 5장 이상', release: 'none', coreAtMost: 24, graveyardMin: 5 },
    onSummon: { kind: 'phase_set', phase: 'dawn' },
    eclipseAffinity: 'dawn',
    eclipseSummonPhases: ['dawn'],
    eclipsePhaseModifiers: { dawn: { attack: 4, health: 4, label: '첫빛 재생' }, midnight: { attack: -1, health: 2, label: '밤샘 기도' } },
    eclipsePhasePulses: [
      { phase: 'dawn', name: '새벽 재기', description: '여명 진입 또는 여명에서 등장 시 묘지 최고 비용 유닛 1체를 체력 60%로 부활시킨다.', effect: { kind: 'revive_best_grave', healthRatio: 0.6, ready: false } },
      { phase: 'dawn', name: '첫빛 치유', description: '여명 진입 또는 여명에서 등장 시 아군 전체 체력 3 회복.', effect: { kind: 'heal_allies', amount: 3 } },
      { phase: 'dawn', name: '일출 행진', description: '여명 진입 또는 여명에서 등장 시 아군 전체를 공격 준비 상태로 만든다.', effect: { kind: 'ready_all' } },
      { phase: 'dawn', name: '여명의 계시', description: '여명 진입 또는 여명에서 등장 시 카드 1장을 드로우한다.', effect: { kind: 'draw', amount: 1 } },
    ],
    temporalProfileName: '여명 지배',
  },
  {
    id: 'v41_premium_eclipse_conductor',
    name: '흑일악사 모르덴',
    subtitle: 'PREMIUM TIME · 흑일을 연주하는 악사',
    kind: 'unit',
    rarity: 'legendary',
    element: 'void',
    cost: 8,
    attack: 11,
    health: 12,
    unitType: 'spirit',
    target: 'none',
    keywords: ['pierce', 'execute', 'charge', 'guard'],
    text: '【고유 특성 · 흑광 대지휘】 개기일식 전용 전설 캐릭터. 【등장】 시간을 개기일식으로 설정하고 2턴 동안 고정한다. 가장 강한 적 1체를 리콜하고, 상대 묘지 1장을 소멸시키며, 상대 ENERGY 1을 흡수한다. 【개기일식 전용 발동】 묘지의 최고 비용 캐릭터 1체를 체력 80%로 부활시키고, 가장 강한 적 1체의 강화와 보호막을 초기화하며, 상대 코어에 4 피해를 주고, 4/4 「흑광 악장」 1체를 소환한다.',
    uniqueTrait: { name: '무광 악장', description: '개기일식의 빛과 소리를 악보처럼 잘라 적의 흐름을 끊는 연주형 고유 특성이다.' },
    flavor: '활 대신 지휘봉을 든 악사가 첫 음을 긋자, 빛이 악보의 쉼표처럼 잘려 나갔다.',
    sigil: '♩',
    summonMode: 'legendary',
    legendarySummonRule: { name: '흑광 조율', label: '묘지 6장 이상 + 아군 유닛 1장 릴리스', release: 'all', minimumAllies: 1, graveyardMin: 6 },
    onSummon: { kind: 'phase_set', phase: 'eclipse' },
    eclipseAffinity: 'eclipse',
    eclipseSummonPhases: ['eclipse'],
    eclipseLifespanPhases: ['eclipse'],
    eclipsePhaseModifiers: { eclipse: { attack: 3, health: 3, label: '흑광 총주' } },
    eclipsePhasePulses: [
      { phase: 'eclipse', name: '저음부 귀환', description: '개기일식 진입 또는 등장 시 내 묘지 최고 비용 유닛 1체를 체력 80%로 부활시킨다.', effect: { kind: 'revive_best_grave', healthRatio: 0.8, ready: false } },
      { phase: 'eclipse', name: '무음 지휘', description: '개기일식 진입 또는 등장 시 가장 강한 적 유닛의 강화 수치와 보호막을 초기화한다.', effect: { kind: 'reset_strongest_enemy' } },
      { phase: 'eclipse', name: '종결 화음', description: '개기일식 진입 또는 등장 시 상대 코어에 4 피해.', effect: { kind: 'damage_core', amount: 4 } },
      { phase: 'eclipse', name: '흑광 악장', description: '개기일식 진입 또는 등장 시 4/4 「흑광 악장」 1체를 소환한다.', effect: { kind: 'summon_token', attack: 4, health: 4, name: '흑광 악장' } },
    ],
    temporalProfileName: '식광 조율',
  },
  {
    id: 'v44_premium_twilight_knight',
    name: '쌍월검사 베스퍼',
    subtitle: 'PREMIUM TIME · 두 달 사이를 걷는 쌍검',
    kind: 'unit',
    rarity: 'legendary',
    element: 'lunar',
    cost: 7,
    attack: 10,
    health: 12,
    unitType: 'vanguard',
    target: 'none',
    keywords: ['guard', 'pierce', 'sweep', 'charge'],
    text: '【고유 특성 · 경계의 맹세】 황혼 전용 전설 캐릭터. 【등장】 시간을 황혼으로 설정하고 카드 1장을 드로우하며, 자신에게 보호막 3을 부여한다. 【황혼 전용 발동】 코어 격차를 최대 5까지 보정하고, 아군 전체 보호막 +2, 상대 코어 2 흡수, 현재 ATK+DEF가 9 이하인 가장 약한 적 1체를 붕괴시킨다. 【황혼 반응】 황혼에서는 +4/+4를 얻는다.',
    uniqueTrait: { name: '쌍월 검무', description: '황혼의 두 경계를 오가며 공격과 방어를 동시에 전환하는 결투형 고유 특성이다.' },
    flavor: '서로 다른 두 달이 떠오르는 순간, 베스퍼의 두 검도 서로 다른 궤적을 그린다.',
    sigil: '⚔',
    summonMode: 'legendary',
    legendarySummonRule: { name: '황혼 서약', label: '내 묘지에 카드가 5장 이상일 때', release: 'none', graveyardMin: 5 },
    onSummon: { kind: 'phase_set', phase: 'dusk' },
    eclipseAffinity: 'dusk',
    eclipseSummonPhases: ['dusk'],
    eclipsePhaseModifiers: { dusk: { attack: 4, health: 4, label: '황혼 기사도' }, eclipse: { attack: 1, health: 2, label: '식광 잔영' }, dawn: { attack: -1, health: 1, label: '새벽의 후퇴' } },
    eclipsePhasePulses: [
      { phase: 'dusk', name: '경계의 저울', description: '황혼 진입 또는 황혼에서 등장 시 코어 격차를 최대 5까지 보정한다.', effect: { kind: 'core_equalize', cap: 5 } },
      { phase: 'dusk', name: '저녁별 방진', description: '황혼 진입 또는 황혼에서 등장 시 아군 전체 보호막 +2.', effect: { kind: 'mass_shield', amount: 2 } },
      { phase: 'dusk', name: '저무는 칼날', description: '황혼 진입 또는 황혼에서 등장 시 상대 코어 2를 흡수한다.', effect: { kind: 'drain_core', amount: 2 } },
      { phase: 'dusk', name: '박명 결투', description: '황혼 진입 또는 황혼에서 등장 시 현재 ATK+DEF 9 이하인 가장 약한 적 1체를 붕괴시킨다.', effect: { kind: 'collapse_weakest_enemy', maxPower: 9 } },
    ],
    temporalProfileName: '황혼 기사도',
  },
  {
    id: 'v41_premium_midnight_silence',
    name: '심야 무성권역',
    subtitle: 'PREMIUM RITUAL · 소리를 지우는 자정 결계',
    kind: 'spell',
    rarity: 'legendary',
    element: 'lunar',
    cost: 6,
    target: 'none',
    text: '【고유 주문 · 무성권역】 심야 전용 의식 주문. 현재 시간을 심야로 설정하고 2턴 동안 고정한다. 모든 적 캐릭터를 1턴 동안 동결시키고, 상대 손패의 최고 비용 카드 1장을 버리게 한다. 그 후 상대 묘지 2장을 소멸시키고 카드 1장을 드로우한다.',
    uniqueTrait: { name: '무성권역', description: '인물이나 소환체가 아니라 전장 전체에 펼쳐지는 자정 봉쇄 의식이다.' },
    flavor: '종이 울리지 않는 자정, 결계문이 닫히며 소리와 명령이 동시에 지워진다.',
    sigil: '∅',
    eclipseAffinity: 'midnight',
    eclipsePlayPhases: ['midnight'],
    effect: { kind: 'phase_set', phase: 'midnight' },
  },
];
